#Makefile: Arianna Vacca

#Target
all: compile
	@echo -e 'Done!'

clean:
	@echo -e 'Cleaning up...'
	@rm -rf cs455/overlay/node/*.class
	@echo -e 'Done!'

compile:
	@echo -e 'Compiling the Source...'
	@javac -d . cs455/overlay/node/*.java